# .github/workflows/restart-heroku.yml
name: Restart Heroku App

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 4 * * *'   # 04:00 UTC
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 16 * * *'  # 16:00 UTC
    - cron: '0 20 * * *'  # 20:00 UTC

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token > /dev/null
          heroku auth:whoami

      - name: Restart dynos
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps:restart --app maventest
